#!/bin/bash

if [ ! -d "dep" ]; then
  mkdir dep
fi

if [ ! -d "bin" ]; then
  mkdir bin
fi

if [ ! -d "dump" ]; then
  mkdir dump
fi

if [ ! -d "vmh-cache" ]; then
  mkdir vmh-cache
fi

mv *.d dep/
cp parc* mt* bin/
for x in bin/*;do maven-objdump -D --disassemble-zeroes --section=.xcpthandler --section=.text --section=.data $x > $x.dump;done
mv bin/*.dump dump/
for x in dump/*;do python ../scripts/objdump2vmh-cache.py -f $x;done
mv dump/*.vmh vmh-cache/
